language: node_js
node_js:
- '4.2'
env:
  global:
  - GH_REF=github.com/drdaemos/prose.git
  - GH_TOKEN=drdaemos
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: qaMNigJo56MfDrMdHCncZ0bHEMPU0q6PxmnBStNGzd+NQGZuY5+7k5RMvA62Y32yh2fpbUIHyRfA4p0WVqAYhRsHyAjuB2J0lyPK7QkPq/vDkJyIFH5dlXcFEv8MLmCAZ0FoOKaPXsXy3xGD9eXSjMnfOPbUcsvBe4XK8ffK65zuI/bJehLfQZxx9tkAvC1tPF8j8YCUm7mxbr672zE30yl7TIGhFrqGhKVYdpRbjxH7BXjxycSRd5VsaVGgJ24Am8kEdpS9sbV8LA1HULct96jAPkL7mUTlewSWXvJqk+kMz5hBYTvVP01kJ6Y2x4DajfIYQt1UFsDs4LKv8aAoVZyUtEGegA9BtN7GR4Qjjeb6XTzZXoIr6XuYidO3KBnsjDxfs0zpRCFVfOYxMB8vYQzq8e8XU8f+qGefW0k2uxnYpmSMrjPmlsowiJoGXSPNskHh1wmSE3jkGMQKPSoCSdfCfb2vKWixFkwzufY2R8JZw6I4TPr8NFzECwIZxvPU8INXmt6DO+2eEqhVpddPPhkocNMLnT8hep50RKI9hRk51nOx5Nz0WBXNpSPWyfuxjcvq3V+IxMkATM+laLs5NZBY3BbBX2UoQJXegI6K9/T3PtsWZZgiUrpdc6bjxp5qODI23mk7WvsOrHBxEtYaej8V7OouGn+YqMn00l4xLQQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- echo -e "Host drdaemos.github.io\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_ff1f83cd9717_key -iv $encrypted_ff1f83cd9717_iv
  -in deploy_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod +x ./.build_scripts/deploy.sh
before_script:
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"